/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.4.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as _schema from "../_schema";
import type * as checkIfExists from "../checkIfExists";
import type * as daySongs from "../daySongs";
import type * as files from "../files";
import type * as morningSongs from "../morningSongs";
import type * as myFunctions from "../myFunctions";
import type * as mySongs from "../mySongs";
import type * as nightSongs from "../nightSongs";
import type * as tasks from "../tasks";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  _schema: typeof _schema;
  checkIfExists: typeof checkIfExists;
  daySongs: typeof daySongs;
  files: typeof files;
  morningSongs: typeof morningSongs;
  myFunctions: typeof myFunctions;
  mySongs: typeof mySongs;
  nightSongs: typeof nightSongs;
  tasks: typeof tasks;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
